### ISSUE TITLE
travis is broken

### ISSUE THREAD

**Issue by stephenmathieson** [duojs/string-to-js#4]

**Comment by dominicbarnes** [comment]
I was just working on fixing that...

**Comment by dominicbarnes** [comment]
Oh, btw I feel like the tests here are messed up.

Since `stoj` is included with duo, the bundled version is what will be run first in the tests. (which means the version configured locally doesn't really do anything. :(

**Comment by dominicbarnes** [comment]
Oh wait... disregard my last comment. Plugins added via `.use()` are mounted before the bundled plugins. I'll have this branch building on CI shortly! :D

**Comment by dominicbarnes** [comment]
Fixed! :D
